import Middleware from "@/app/Middleware";
import type { Metadata } from "next";
import Sidebar from "@/ui/molecules/Sidebar/Sidebar";
import { HeaderDashboard } from "@/ui/organisms";
import "./styles.scss";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>){
    return (
        <html lang="en">
            <body className={""}>
              <div className="dashboard">
                <Sidebar />
                <HeaderDashboard />
                {children}
              </div>
            </body>
        </html>
    )
}